spring:
  application:
    name: admin_server
  boot:
    admin:
      client:
        url: http://127.0.0.1:9999
server:
  port: 9999




management:
  endpoints:
    web:
      exposure:
        include: '*'  # 对外暴露的访问入口 , 默认是/health和/info
  endpoint:
    health:
      show-details: always    # 显示所有健康状态
  info:
    env:
      enabled: true
  # 管理端口
#  server:
#    port: 9090


# http://docs.spring-boot-admin.com/2.7.10/
