spring:
  boot:
    admin:
      client:
        url: http://127.0.0.1:9999
        instance:
          service-base-url: http://127.0.0.1:9090

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always    # 显示所有健康状态
    shutdown:
      enabled: true # curl http://127.0.0.1:9090/actuator/shutdown -X POST
  info:
    env:
      enabled: true
  # 管理端口
  server:
    port: 9090


# http://docs.spring-boot-admin.com/2.7.10/
