spring:
  profiles:
    include:
      adminClient
      ,sqlite
#      ,mysql
  #    active: pro
  jpa:
    hibernate:
      # 自动生成DDL的执行时机
      ddl-auto: update
      # 命名策略大写变下划线
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: false
    # 根据实体类创建DDL语句，自动生成数据库
    generate-ddl: true
    open-in-view: true
  #    database: mysql
  application:
    name: study_admin_client
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false

server:
  port: 8080
#  servlet:
#    context-path: /servletDemo

# 精确控制SQL日志级别，减少无用日志输出
logging:
  level:
    #    com.xjdl : info # 指定包的日志级别
    sql: debug
#JVM启动参数配置
#-Xms500m -Xmx500m
