spring:
  profiles:
    include:
      adminclient
      ,cache
      ,datasource
      ,hikari
      ,jackson
      ,jpa
      ,mybatisplus
      ,myconfig
      ,springdoc
      ,task
      ,undertow
  #    active: pro
  application:
    name: study_admin_client
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /**

server:
  port: 8080
#  servlet:
#    context-path: /servletDemo

# 精确控制SQL日志级别，减少无用日志输出
logging:
  level:
    com.xjdl.study.myBatisPlus: debug # MybatisPlus的SQL日志配置方式，trace级别会在日志文件中记录，控制台只有debug级别日志
    sql: debug
#JVM启动参数配置
#-Xms500m -Xmx500m

