# 先读取yaml文件，后读取properties文件
newperson:
  name: 'xjdl \n' # 单引号不会转义
  age: 99
  child: # Obj
    name: "goudan \n" # 双引号会转义
    age: 32
    #    desc: qw, er
    desc:
      - qw
      - er
      - |
        大文本读取，| 保持原有格式
        aaaaaaaaaa
        bbbbbbbbbb
        cccccccccc
      - >
        大文本读取，> 压缩换行的格式
        aaaaaaaaaa
        vvvvvvvvvv
        gggggggggg
  dog: # List
    - name: dog1
      age: 65
    - name: dog2
      age: 3
  cat: # Map
    cat1:
      name: zx
      age: 4
    cat2:
      name: cv
      age: 3
--- # 使用分隔符分离单个文档
xjdl:
  apis:
    lunardate:
      desc: 公历与农历对照表 ?date={yyyy-MM-dd}
      baseUrl: https://data.weather.gov.hk/weatherAPI/opendata/lunardate.php
      data: date
      method: GET
    nstool:
      desc: 网易DNS检测工具
      base-url: http://www.nstool.netease.com/
      data:
      method: GET
  banner:
    location: classpath:xjdl_banner.txt
  bot:
    words:
      Hello! My name is Bot.
  ver:
    Your SpringBoot application name is ${spring.application.name:Give your application a name}