spring:
  profiles:
    include:
      adminclient
      ,cache
      ,datasource
      ,hikari
      ,jackson
      ,jpa
      ,mybatisplus
      ,myconfig
      ,springdoc
      ,task
      ,undertow
  #    active: pro
  application:
    name: study_admin_client
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /**
    contentnegotiation:
      favor-parameter: true # 开启基于请求参数的内容协商功能，默认不开启
      parameter-name: format # ("format" by default)
      media-types:
        # 对象格式的媒体类型
        "yaml": text/yaml

server:
  port: 8080
  error:
    path: /error #默认的错误处理路径
#  servlet:
#    context-path: /servletDemo

# 精确控制SQL日志级别，减少无用日志输出
logging:
  level:
    sql: debug
    com.xjdl.study.myBatisPlus: debug # MybatisPlus的SQL日志配置方式，trace级别会在日志文件中记录，控制台只有debug级别日志
    # 打印 hibernate SQL参数
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    # 打印 hibernate SQL字段
#    org.hibernate.type.descriptor.sql.BasicExtractor: trace
#JVM启动参数配置
#-Xms500m -Xmx500m org.hibernate.type.descriptor.sql.BasicBinder
