spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:db/db.sqlite?date_string_format=yyyy-MM-dd HH:mm:ss
    type: com.zaxxer.hikari.HikariDataSource

#    username: root
#    password: root
#    #高版本 Mysql 驱动时，配置的 driver-class-name 不再是 com.mysql.jdbc.Driver，url 后面必须设置时区 serverTimezone
#    url: jdbc:mysql:///mybatis-plus?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.ha.HighAvailableDataSource
