spring:
  datasource:
    # jdbc 连接基础配置
    # sqlite
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:db.sqlite
    type: com.zaxxer.hikari.HikariDataSource

    # mysql
#    username: root
#    password: root
#    #高版本 Mysql 驱动时，配置的 driver-class-name 不再是 com.mysql.jdbc.Driver，url 后面必须设置时区 serverTimezone
#    url: jdbc:mysql:///springboot?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.ha.HighAvailableDataSource
