spring:
  profiles:
    include:
      adminclient
      ,datasource
      ,hikari
      ,jackson
      ,jpa
      ,mybatisplus
      ,springdoc
      ,undertow
  #    active: pro
  application:
    name: study_admin_client
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /**

server:
  port: 8080
#  servlet:
#    context-path: /servletDemo

# 精确控制SQL日志级别，减少无用日志输出
logging:
  level:
    com.xjdl.study.myBatisPlus: trace
    sql: debug
#JVM启动参数配置
#-Xms500m -Xmx500m

