name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

#      - name: Build with Maven1
#        run: mvn clean install -pl com.xjdl:xjdl-spring-boot-starter -am -DskipTests=true -e -X

#      - name: Build with Maven2
#        run: mvn clean install -DskipTests=true -pl com.xjdl:study -am -T 1C

#      - name: Run jar
#        run: java -jar /home/runner/work/loaf/loaf/study/target/study-1.0.jar
